name: Sync Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mobile repo
      uses: actions/checkout@v2
      with:
        repository: Azeras007/flowz

    - name: Add organization repo as remote
      run: git remote add upstream https://github.com/EpitechPromo2027/B-DEV-500-MPL-5-1-area-elliot.feuilllade/tree/main/client_mobile  # Remplacer par le dépôt de l'organisation

    - name: Fetch changes from upstream
      run: git fetch upstream

    - name: Merge changes from upstream
      run: git merge upstream/main --allow-unrelated-histories

    - name: Push changes to mobile repo
      run: |
        git push origin main