name: Sync Repo

on:
  push:
    branches-ignore:
      - ga-ignore-*
  pull_request:
    branches-ignore:
      - ga-ignore-*

env:
  MIRROR_URL: git@github.com:Azeras007/flowz.git

jobs:

  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Epitech org repo
        uses: actions/checkout@v3
        with:
          repository: EpitechPromo2027/B-DEV-500-MPL-5-1-area-elliot.feuilllade

      - name: Push to public repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

    - name: Push changes to mobile repo
      run: |
        git push origin main
